### ISSUE TITLE
how to retrieve the image from midjourney bot?

### ISSUE THREAD

**Issue by hoveychen** [hongliang5316/midjourney-go#1]
It would be necessary to have a way to retrieve the generated result to build a complete API

**Comment by hongliang5316** [comment]
@hoveychen 
Hello, this library is only used as a command API for `midjourney bot`, the output of `midjourney bot` is in discord, if you want to get the output of `midjourney bot` out of discord, i suggest you to take a look at this project [midjourney-apiserver](https://github.com/hongliang5316/midjourney-apiserver).
